Team-walkies/Walkie-Android

- app/build.gradle.kts
- app/proguard-rules.pro
- build-logic/convention/src/main/java/com/startup/convention/walkie.android.library.gradle.kts
- build-logic/convention/src/main/java/com/startup/convention/walkie/Android.kt
- Resolved : #149 
- Android Module minify 처리 X, App Module 에서만 처리해도 됨
- proguard.pro 파일 추가
-
> #149 R8 shrinking, obfuscation 이슈 처리

- core/data/src/main/java/com/startup/data/datasource/MemberDataSource.kt
- core/data/src/main/java/com/startup/data/remote/datasourceimpl/MemberDataSourceImpl.kt
- core/data/src/main/java/com/startup/data/remote/service/MemberService.kt
- core/data/src/main/java/com/startup/data/repository/MemberRepositoryImpl.kt
- core/domain/src/main/java/com/startup/domain/repository/MemberRepository.kt
- core/domain/src/main/java/com/startup/domain/usecase/GetRecordedSpotCount.kt
- feature/home/src/main/java/com/startup/home/HomeActivity.kt
- feature/home/src/main/java/com/startup/home/MainBottomNavigationScreen.kt
- feature/home/src/main/java/com/startup/home/MainContract.kt
- feature/home/src/main/java/com/startup/home/main/HomeScreen.kt
- feature/home/src/main/java/com/startup/home/main/HomeViewModel.kt
- feature/spot/src/main/java/com/startup/spot/SpotActivity.kt
- feature/spot/src/main/java/com/startup/spot/SpotContract.kt
- feature/spot/src/main/java/com/startup/spot/SpotViewModel.kt
- feature/spot/src/main/java/com/startup/spot/navigation/SpotModuleNavigatorImpl.kt
- navigation/src/main/java/com/startup/navigation/SpotModuleNavigator.kt
- Resolved : #153 
- 이슈에서 언급한 작업 (backstack 추적하여 refresh)
- 스팟 리뷰 수 api 나왔길래 연동
- 스팟 탐험 후 refresh 되도록 추가하였습니다.
- UserInfo BaseUiState 에서 제거했는데 기존에 연결하신 processUserInfo() 에는 영향 없는지 체크 부탁드려요
> #153 홈 리프레시 조건 추가

- core/common/src/main/java/com/startup/common/extension/ContextExtension.kt
- feature/home/src/main/java/com/startup/home/main/HomeScreen.kt
- feature/home/src/main/java/com/startup/home/main/HomeViewModel.kt
- Resolved : #148 
- 위치권한 허용 알럿에서 [13차 회의](https://www.notion.so/13-1e3e3ac17cda80a98323e68c89680e39?pvs=4)때 논의되었던 대로 랜딩지점 수정하였습니다.
-
https://github.com/user-attachments/assets/1ed89b76-45f0-45ca-96f8-f9c630d40b2d
> #148 위치권한 알럿 [항상 허용] 랜딩 지점 수정 / 알 부화 이후 걸음수 업로드 및 리프레시 로직 추가

- core/common/src/main/java/com/startup/common/util/DateUtil.kt
- core/data/src/main/java/com/startup/data/remote/dto/response/character/AcquisitionCharacterInfoResponse.kt
- core/data/src/main/java/com/startup/data/remote/dto/response/character/AcquisitionInfo.kt
- core/domain/src/main/java/com/startup/domain/model/character/CharacterDetail.kt
- core/domain/src/main/java/com/startup/domain/model/character/CharacterObtainInfo.kt
- core/domain/src/main/java/com/startup/domain/usecase/GetHatchedCharacterDetail.kt
- core/resource/src/main/res/values/strings.xml
- feature/home/src/main/java/com/startup/home/character/HatchingCharacterScreen.kt
- feature/home/src/main/java/com/startup/home/character/HatchingCharacterViewModel.kt
- feature/home/src/main/java/com/startup/home/character/model/HatchingCharacterContract.kt
- feature/home/src/main/java/com/startup/home/character/model/WalkieCharacterDetail.kt
- feature/home/src/main/java/com/startup/home/navigation/HomeNavigationGraph.kt
- Resolved : #162
- 캐릭터 획득 정보 api 연동 했습니다.
- picked 유무가 오지 않아... viewingCharacter 필드는 일단 유지했습니다..!(picked 유무 체크)
- DateUtil 에 yyyy.MM.dd 추가, 나중에 빌더 패턴으로 하던지 해야할듯
- uiModel 생성
-
https://github.com/user-attachments/assets/77245515-23f4-489c-a5e6-3c8070cfd754
> #162 캐릭터 상세 부화 기록 api 연동

- core/common/src/main/java/com/startup/common/event/EventContainer.kt
- feature/home/src/main/java/com/startup/home/HomeActivity.kt
- feature/home/src/main/java/com/startup/home/MainBottomNavigationScreen.kt
- feature/home/src/main/java/com/startup/home/MainContract.kt
- feature/home/src/main/java/com/startup/home/character/HatchingCharacterViewModel.kt
- feature/home/src/main/java/com/startup/home/egg/GainEggViewModel.kt
- feature/home/src/main/java/com/startup/home/main/HomeViewModel.kt
- feature/home/src/main/java/com/startup/home/navigation/MyPageNavigationGraph.kt
- feature/login/src/main/kotlin/com/startup/login/login/LoginActivity.kt
- feature/spot/src/main/java/com/startup/spot/SpotScreen.kt
- feature/spot/src/main/java/com/startup/spot/modify/ModifySpotScreen.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/service/WalkieStepForegroundService.kt
- Resolved : #166
- 알 선택, 캐릭터 선택 시 다른 스크린에서 이벤트를 감지해야해서 EventContainer 같이 활용 했습니다(추후 변경 필요)
- state 관련해서 같이 걷는 알, 같이 걷는 캐릭터 관련해서도 이벤트 감지로 리프레시 하도록 추가했습니다!
https://github.com/user-attachments/assets/971760b6-42a7-4db7-b670-705be210aee3
> #166 fix : 캐릭터, 알 선택 시 홈 리프레시

- core/common/src/main/java/com/startup/common/util/CustomExceptions.kt
- core/design-system/src/main/java/com/startup/design_system/widget/modal/ErrorModal.kt
- core/resource/src/main/res/values/strings.xml
- feature/login/src/main/kotlin/com/startup/login/login/LoginActivity.kt
- feature/login/src/main/kotlin/com/startup/login/login/LoginViewModel.kt
- 401 에러가 내려올 때에 알럿을 표출해주기 위해 UserAccountWithdrawnException 클래스 생성
- 급한대로 Exception 아무거나 새로 만들었는데, 나중에는 WalkieException 이 아닌 DialogException 을 상속 받아서 처리 해야 할 것 같아요!
-
> fix : 회원 탈퇴 후 로그인 시도 시 알럿 표출 로직 추가

- core/design-system/src/main/java/com/startup/design_system/widget/modal/ErrorModal.kt
- core/resource/src/main/res/values/strings.xml
- feature/login/src/main/kotlin/com/startup/login/login/LoginActivity.kt
- Resolved : #181 
- 탈퇴 관련 알럿에 제목 추가했숩니닷 크게 달라진건 없고 title 만 새로 생겼습니다!
> #181 [QA] 알럿에 제목 추가

- feature/home/src/main/java/com/startup/home/navigation/HomeModuleNavigatorImpl.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/notification/WalkieNotification.kt
- Resolved : #199 
- 테스크 다 날리도록 변경하였습니다!
-
> #199 알림으로 앱 접근 시 홈 화면 2개 있음

- core/common/src/main/java/com/startup/common/event/EventContainer.kt
- feature/home/src/main/java/com/startup/home/egg/GainEggViewModel.kt
- feature/home/src/main/java/com/startup/home/main/HomeViewModel.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/notification/WalkieNotification.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/service/WalkieStepForegroundService.kt
- Resolved : #198
- 목표걸음수 제대로 페칭 안되는거 해결하였습니다. 
- 추가적으로 목표걸음수에 따라 알림 바로 바뀌도록 했습니다.
- 앱 삭제후 목표걸음수 설정 되는 것도 확인
- 백그라운드
https://github.com/user-attachments/assets/1fc3fc5f-5ffb-4133-8190-9fee710ea7ff
- 포그라운드
https://github.com/user-attachments/assets/75758a8e-7b77-4ba0-9046-b1471f6f46cd
> #198 목표걸음수 타이밍 이슈 해결 및 알 변경시 알림 바뀌는 기능 추가

- core/resource/src/main/res/values-v35/theme.xml
- core/resource/src/main/res/values/strings.xml
- Resolved : #197 
- 위치 항상 허용 팝업 문구 변경 하고 안드로이드 15 기기 이전에는 windowLightStatusBar 값 강제로 true로 되지 않도록 추가했습니다.
-
> #197 위치 항상 허용 팝업 문구 변경 / theme.xml 버전 분기

- feature/home/src/main/java/com/startup/home/HomeActivity.kt
- feature/home/src/main/java/com/startup/home/main/HomeViewModel.kt
- feature/home/src/main/java/com/startup/home/main/screen/HomeScreen.kt
- feature/home/src/main/java/com/startup/home/permission/PermissionManager.kt
- feature/home/src/main/java/com/startup/home/permission/PermissionUiComponent.kt
- feature/home/src/main/java/com/startup/home/permission/PermissionUiEvent.kt
- Resolved : #208 
- 기능은 유지한채 권한 바텀시트 파일간 관심사 및 activity 의존성들 제거 하였습니다.
- 추가로 개선할 사항있으면 더 제안해주세요! 해당 PR 에서 한번에 하려고 합니다.
> #208 PermissionManager Activity 간 관심사 분리

- core/domain/src/main/java/com/startup/domain/provider/DateChangeListener.kt
- core/domain/src/main/java/com/startup/domain/provider/DateChangeNotifier.kt
- core/domain/src/main/java/com/startup/domain/provider/StepCounterService.kt
- feature/home/build.gradle.kts
- feature/home/src/main/java/com/startup/home/HomeActivity.kt
- feature/home/src/main/java/com/startup/home/main/HomeViewModel.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/broadcastReciver/BootCompletedReceiver.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/broadcastReciver/DailyResetReceiver.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/broadcastReciver/PackageChangedReceiver.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/broadcastReciver/RestartServiceReceiver.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/di/StepCounterServiceModule.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/navigation/StepCounterControllerImpl.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/service/ServiceUtil.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/service/StepCounterServiceImpl.kt
- Resolved : #185 
- Home 모듈에서 stepcounter 의존성 제거하고 datastore와 유사하게 domain 모듈을 통해서 접근하도록 수정했습니다. 
- 기존 ServiceUtil 네이밍도 조금 더 명확하게 수정하였습니다.
> #185 home 모듈에서 :feature:stepcounter 모듈 제거 / ServiceUtil 네이밍 수정

- feature/home/src/main/java/com/startup/home/mypage/screen/PushSettingScreen.kt
- Resolved : #214
- 토글이 바라보는 값이 달랐음
- 스팟 도착 알림도 제거
> #214 푸시알림 설정 토글 안되는 오류

- app/src/main/kotlin/com/startup/walkie/WalkieApplication.kt
- core/common/src/main/java/com/startup/common/util/PackageManagerCompat.kt
- core/data/build.gradle.kts
- core/data/src/main/java/com/startup/data/di/NetworkModule.kt
- core/data/src/main/java/com/startup/data/repository/UserRepositoryImpl.kt
- core/design-system/src/main/java/com/startup/design_system/widget/modal/ErrorModal.kt
- core/design-system/src/main/java/com/startup/design_system/widget/modal/ErrorTwoButtonModal.kt
- core/design-system/src/main/java/com/startup/design_system/widget/modal/PrimaryModal.kt
- core/design-system/src/main/java/com/startup/design_system/widget/modal/PrimaryTwoButtonModal.kt
- core/domain/src/main/java/com/startup/domain/repository/UserRepository.kt
- core/domain/src/main/java/com/startup/domain/usecase/notification/GetAppMinVersionCode.kt
- core/resource/src/main/res/values/strings.xml
- core/resource/src/main/res/xml/remote_config_defaults.xml
- feature/login/src/main/kotlin/com/startup/login/splash/SplashActivity.kt
- feature/login/src/main/kotlin/com/startup/login/splash/SplashContract.kt
- feature/login/src/main/kotlin/com/startup/login/splash/SplashViewModel.kt
- Resolved : #43
- 급하게 만드느라 부족한 부분들이 조금씩 있을 수도 있습니다..!
- remoteConfig 연동
- PrimaryModal 조건 추가
- 스플래시에서 minVersion 체크
- minimumFetchIntervalInSeconds = 3600 조건 어떻게 할까유??
- UserRepositoryImpl 에서 getMinAppVersionCode() 가져오는 로직 확인해주세요! (결과가 오지 않는 경우가 생겨 무한정 기다림이 생길지)
https://github.com/user-attachments/assets/5a49ce7a-1064-4666-8cac-c02c1ea14062
> #43 앱 최소버전 Block 로직 구현

- core/data/src/main/java/com/startup/data/remote/dto/response/egg/EggDto.kt
- core/domain/src/main/java/com/startup/domain/model/egg/MyEgg.kt
- core/model/src/main/java/com/startup/model/egg/MyEggModel.kt
- Resolved : #220 
- characterRank 가 없었어서 추가하는 과정에서 rank 가 사라졌네요,, 추가했습니다
> #220 알 등급 오류

- app/build.gradle.kts
- gradle/libs.versions.toml
- Resolved : #219 
- LeakCanary 탑재 하였습니다. 
- 간단하게 확인이 아직 메모리 누수는 없는 것 같습니다 👍
> #219 leakcanary 탑재

- core/design-system/src/main/java/com/startup/design_system/widget/bottom_sheet/ForceUpdateBottomSheet.kt
- core/resource/src/main/res/values/strings.xml
- feature/login/src/main/kotlin/com/startup/login/splash/SplashActivity.kt
- feature/login/src/main/kotlin/com/startup/login/splash/SplashContract.kt
- Resolved : #225
- 강제업데이트 바텀시트 추가하였습니다. 
- dim영역 터치 혹은 drag 등의 동작을 막으려고 Box활용해서 레이아웃 구성하였습니다.
https://github.com/user-attachments/assets/094e3f2f-6f45-4778-8703-d1525e7b83ad
> #225 강제업데이트 바텀시트 추가

- feature/home/src/main/java/com/startup/home/character/HatchingCharacterScreen.kt
- Resolved : #229 
- 크게 작업한건 없습니다!! 자세히 보니 페이저 양쪽 여백이 없어 딱 붙어서 페이저 전환 되는거 패딩 주었고, pagerState.animateScrollToPage 에 animationSpec 추가하여 duration 추가했습니다
-
https://github.com/user-attachments/assets/c667d454-d8a4-44e0-9d4f-4278d06b4a4e
> #229 부화한캐릭터 - 페이저 넘길 때 전환 애니메이션 duration 지정

- core/common/src/main/java/com/startup/common/extension/ComposeExtension.kt
- core/data/src/main/java/com/startup/data/remote/dto/response/character/AcquisitionCharacterInfoResponse.kt
- core/domain/src/main/java/com/startup/domain/model/character/CharacterDetail.kt
- core/model/src/main/java/com/startup/model/character/WalkieCharacterDetail.kt
- feature/home/src/main/java/com/startup/home/character/HatchingCharacterScreen.kt
- feature/home/src/main/java/com/startup/home/character/HatchingCharacterViewModel.kt
- Resolved : #231 
- name, description, imageUrl 추가했습니다.
- 이미지 부분 위쪽이 스켈레톤으로 되면서 스켈레톤 디자인이 어느정도 바뀌었습니다. 아래 첨부 이미지에 설명 있습니다.
- 스켈레톤 처리 방식이 조금 다릅니다. default showShimmer = false
https://github.com/user-attachments/assets/34485278-9c12-4def-baf0-c9ea26f5c743
> #231 캐릭터 설명 및 캐릭터 이미지 field 추가 및 UI 변경 건 작업

- core/common/src/main/java/com/startup/common/util/DateUtil.kt
- core/data/src/main/java/com/startup/data/di/DataStoreModule.kt
- core/data/src/main/java/com/startup/data/di/NetworkModule.kt
- core/data/src/main/java/com/startup/data/remote/datasourceimpl/StepDataStoreImpl.kt
- core/data/src/main/java/com/startup/data/remote/dto/request/healthcare/PutTodayWalkRequest.kt
- core/data/src/main/java/com/startup/data/remote/dto/response/healthcare/PutTodayWalkDto.kt
- core/data/src/main/java/com/startup/data/remote/service/HealthcareService.kt
- core/domain/src/main/java/com/startup/domain/model/healthcare/TodayWalk.kt
- core/domain/src/main/java/com/startup/domain/provider/StepDataStore.kt
- feature/stepcounter/src/main/java/com/startup/stepcounter/service/WalkieStepForegroundService.kt
- Resolved : #246 
- 걸음 수 초기화 하는 부분에 날짜가 바뀐 경우에 전날 기록하던 날짜 기반으로 업데이트 하도록 추가했습니다.
- StepDateStore 부분이 remote 처리도 하기에 local 에서 remote 로 옮겼습니다, 분리해서 하기엔 StepDateStore 에 너무 의존을 하고 있기도 하고 DailyResetReceiver 에도 걸음 수 초기화 하는 부분이 엮여 있어서 StepDateStoreImpl 내부에 같이 구현했습니다,,
- 여기 나중에 분리를 좀 해야할 것 같아요..!
- 아무래도 관련 흐름의 대부분의 로직을 제가 작성한게 아니다보니 호출하는 시점이나 값 보내는게 괜찮은지 체크 좀 잘 부탁드려요!
> #246 헬스 케어 걸음 수 저장 API 선 개발
